name: Build - Windows

on: [push]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'
      - name: Build
        run: dotnet build --configuration Release --arch x64 KulectorUI