name: Build - Windows

on: [push]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'
      - name: Build
        run: dotnet build --configuration Release --arch x64 KulectorUI
      - name: Remove debug artifacts
        run: | 
        rm KulectorUI/bin/Release/net6.0-windows/win-x64/KulectorDB.pdb
        rm KulectorUI/bin/Release/net6.0-windows/win-x64/KulectorExternalApis.pdb
        rm KulectorUI/bin/Release/net6.0-windows/win-x64/KulectorUI.pdb
      - uses: vimtor/action-zip@v1
        name: Zip the build
        with: 
          files: KulectorUI/bin/Release/net6.0-windows/win-x64/
          dest: Kulector-${{ github.ref_name }}-${{ github.sha }}-Win64.zip
        
